[package]
name = "wolff"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rustyline = "10.0.0"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"